# Generated by Django 5.0.4 on 2025-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('college', 'College'), ('department', 'Department'), ('industry', 'Industry')], max_length=50)),
                ('sub_department', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('document', models.FileField(null=True, upload_to='mou_documents/')),
            ],
            options={
                'db_table': 'mou',
            },
        ),
    ]
